#!/bin/sh

DAEMON="/usr/sbin/edge"
prog=edge
MODULE="tun"
CONFIGFILE="/etc/n2n/edge.conf"

test -e $DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting $prog"
    # Make sure kernel module is loaded
    if [ ! -c /dev/net/tun ]
    then
        # Try load the kernel module fail if we can't
        modprobe $MODULE >/dev/null 2>&1
        if [ $? -eq 1 ]
        then
            echo "Error: failed to load $MODULE module."
            return 1
        fi
    fi
    start-stop-daemon --start --quiet --background --exec $DAEMON $CONFIGFILE 
    echo "."
    ;;
  stop)
    echo -n "Stopping $prog"
    start-stop-daemon --stop --quiet --exec $DAEMON
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --signal 1 --exec $DAEMON
    ;;
  restart)
    $0 stop
    sleep 1
    echo ""
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/$prog {start|stop|reload|restart|force-reload}"
    exit 1
esac
